name: Deploy to Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: production_environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238447548277:role/github-deploy-meriemterki-aws-resume-api
          role-session-name: github-deployment
          aws-region: us-east-1 # Replace with your AWS region

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          function_name: "FetchResumeFunction" # Replace with your Lambda function name
          zip_file: "src/lambda_function.zip" # Replace with the path to your ZIP file

      - name: Initialize Terraform
        run: terraform init
        working-directory: . # Set this to the directory where your Terraform files are located

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: . # Set this to the directory where your Terraform files are located

      - name: Output API URL
        id: output
        run: |
          terraform output -json > outputs.json
          cat outputs.json

      - name: Set API URL as environment variable
        run: echo "API_URL=$(jq -r .api_url.value < outputs.json)" >> $GITHUB_ENV
